---
  name: Linters

  on:  # yamllint disable-line rule:truthy
    pull_request:

    push:
      branches:
        - master

  jobs:
    doc8:
      name: doc8
      runs-on: ubuntu-latest

      steps:
        - name: Check out repo
          uses: actions/checkout@v3

        - name: Run doc8
          uses: containerbuildsystem/actions/doc8@master
